### ISSUE TITLE
cannot run example

### ISSUE THREAD

**Issue by manask88** [exponentjs/ex-navigation#10]
I have tried running the example as per the instructions in the readme.

However, I get this error:

 ERROR  Unexpected token ...
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (.../routing/ex-navigation/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at new Bundler (index.js:120:27)
    at new Server (index.js:207:21)

Any idea on what is going on?

**Comment by brentvatne** [comment]
Hey there! I converted the example app to run on Exponent now, check out the README again and you should be good to go. Thanks!
