### ISSUE TITLE
frech clone of the project, example don't run

### ISSUE THREAD

**Issue by gre** [exponentjs/ex-navigation#134]
```bash
git clone
cd example
npm install
# open in exponent XDE
```

crashes

```

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ExNavigationExample
  Paths: /Users/gre/dev/ex-navigation/example/package.json collides with /Users/gre/dev/ex-navigation/example/SharedElementTransitionsExample/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: ExNavigationExample
  Paths: /Users/gre/dev/ex-navigation/example/package.json collides with /Users/gre/dev/ex-navigation/example/SharedElementTransitionsExample/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/gre/dev/ex-navigation/example/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:155:13)
    at p.getName.then.name (/Users/gre/dev/ex-navigation/example/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:130:31)

```

**Comment by brentvatne** [comment]
Ah sorry about that, fixed now in 5d6654a25b782dbe81cd0df938953e1dba8818f4
