### ISSUE TITLE
Opening ExNavigationExample in XDE gives Error: Problem in exp.json. child "ios" fails because ["permissions" is not allowed]

### ISSUE THREAD

**Issue by shanecav** [exponentjs/ex-navigation#28]
I'm using a fresh clone of ex-navigation. I ran `cd example/ExNavigationExample && npm install`. When I open the project in XDE (2.4.0), I see the error:

> _Error: Problem in exp.json. child "ios" fails because ["permissions" is not allowed]. See https://docs.getexponent.com/.
> Couldn't start project. Please fix the above issues and restart the project._

If I delete the entire `permissions` section under `ios` in exp.json, the project will open ok, but then shows the following error when I open it in the iOS simulator:
```
[node-haste] Encountered an error while persisting cache:
SyntaxError: /path/to/ex-navigation/example/ExNavigationExample/node_modules/exponent/src/Exponent.js: Unexpected token (22:9)

20 | import './Logs';
21 | 
22 | export * as Constants from './Constants';
   |          ^
23 | export * as Contacts from './Contacts';
24 | export * as Asset from './Asset';
25 | export * as Font from './Font';

> at Parser.pp.raise (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/location.js:22:13)
> at Parser.pp.unexpected (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/util.js:89:8)
> at Parser.pp.parseExportFrom (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/statement.js:938:12)
> at Parser.pp.parseExport (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/statement.js:861:12)
> at Parser.parseExport (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/plugins/flow.js:107:20)
> at Parser.pp.parseStatement (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/statement.js:141:81)
> at Parser.parseStatement (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/plugins/flow.js:30:22)
> at Parser.pp.parseBlockBody (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/statement.js:529:21)
> at Parser.pp.parseTopLevel (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/statement.js:36:8)
> at Parser.parse (/path/to/ex-navigation/example/ExNavigationExample/node_modules/babylon/lib/parser/index.js:129:19)
```

Not sure if it's relevant, but I did run a previous version of this example last week without any issues.

Let me know if there's any other information I can provide. Happy to help out however I can, but I'm pretty new to Exponent and ex-navigation so my knowledge is limited at this point.

**Comment by sibelius** [comment]
@shanecav is this still happening?

I've tried today and it is working fine

**Comment by shanecav** [comment]
@sibelius I hadn't tried again since I first opened the issue, but I just gave it a shot and it looks like both examples work well, so I'll close this.
