### ISSUE TITLE
'@exponent/ex-navigation' is not in the npm registry

### ISSUE THREAD

**Issue by jonlaing** [exponentjs/ex-navigation#292]
I've now tried this on my home computer and my work computer. The issue seems to come up the same. I can download other packages just fine, but all exponentjs modules seem to give me trouble.

This is from a fresh project, nothing in it:
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/jon.laing/.nvm/versions/node/v6.5.0/bin/node" "/Users/jon.laing/.nvm/versions/node/v6.5.0/bin/npm" "install" "--save" "@exponent/ex-navigation" "--registry=https://registry.npmjs.org/"
npm ERR! node v6.5.0
npm ERR! npm  v2.15.6
npm ERR! code E404

npm ERR! 404 User not found : @exponent/ex-navigation
npm ERR! 404
npm ERR! 404 '@exponent/ex-navigation' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jon.laing/projects/fakeproj/npm-debug.log
```

Thanks in advance.

**Comment by jonlaing** [comment]
This is the npm-log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jon.laing/.nvm/versions/node/v6.5.0/bin/node',
1 verbose cli   '/Users/jon.laing/.nvm/versions/node/v6.5.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@exponent/ex-navigation',
1 verbose cli   '--registry=https://registry.npmjs.org/' ]
2 info using npm@2.15.6
3 info using node@v6.5.0
4 verbose install initial load of /Users/jon.laing/projects/fakeproj/package.json
5 verbose readDependencies loading dependencies from /Users/jon.laing/projects/fakeproj/package.json
6 silly cache add args [ '@exponent/ex-navigation', null ]
7 verbose cache add spec @exponent/ex-navigation
8 silly cache add parsed spec Result {
8 silly cache add   raw: '@exponent/ex-navigation',
8 silly cache add   scope: '@exponent',
8 silly cache add   name: '@exponent/ex-navigation',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed @exponent/ex-navigation@latest
10 verbose addNamed "latest" is being treated as a dist-tag for @exponent/ex-navigation
11 info addNameTag [ '@exponent/ex-navigation', 'latest' ]
12 silly mapToRegistry name @exponent/ex-navigation
13 silly mapToRegistry scope (from package name) @exponent
14 verbose mapToRegistry no registry URL found in name for scope @exponent
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry data Result {
17 silly mapToRegistry   raw: '@exponent/ex-navigation',
17 silly mapToRegistry   scope: '@exponent',
17 silly mapToRegistry   name: '@exponent/ex-navigation',
17 silly mapToRegistry   rawSpec: '',
17 silly mapToRegistry   spec: 'latest',
17 silly mapToRegistry   type: 'tag' }
18 silly mapToRegistry uri https://registry.npmjs.org/@exponent%2fex-navigation
19 verbose addNameTag registry:https://registry.npmjs.org/@exponent%2fex-navigation not in flight; fetching
20 verbose request uri https://registry.npmjs.org/@exponent%2fex-navigation
21 verbose request always-auth set; sending authorization
22 info attempt registry request try #1 at 10:44:03 AM
23 verbose request id 59d111287c49b6ad
24 http request GET https://registry.npmjs.org/@exponent%2fex-navigation
25 http 404 https://registry.npmjs.org/@exponent%2fex-navigation
26 verbose headers { 'content-type': 'application/json',
26 verbose headers   'cache-control': 'max-age=0',
26 verbose headers   'content-length': '26',
26 verbose headers   'accept-ranges': 'bytes',
26 verbose headers   date: 'Mon, 05 Dec 2016 15:38:08 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-jfk8121-JFK',
26 verbose headers   'x-cache': 'MISS',
26 verbose headers   'x-cache-hits': '0',
26 verbose headers   'x-timer': 'S1480952288.300879,VS0,VE368' }
27 silly get cb [ 404,
27 silly get   { 'content-type': 'application/json',
27 silly get     'cache-control': 'max-age=0',
27 silly get     'content-length': '26',
27 silly get     'accept-ranges': 'bytes',
27 silly get     date: 'Mon, 05 Dec 2016 15:38:08 GMT',
27 silly get     via: '1.1 varnish',
27 silly get     connection: 'keep-alive',
27 silly get     'x-served-by': 'cache-jfk8121-JFK',
27 silly get     'x-cache': 'MISS',
27 silly get     'x-cache-hits': '0',
27 silly get     'x-timer': 'S1480952288.300879,VS0,VE368' } ]
28 verbose stack Error: User not found : @exponent/ex-navigation
28 verbose stack     at makeError (/Users/jon.laing/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
28 verbose stack     at CachingRegistryClient.<anonymous> (/Users/jon.laing/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
28 verbose stack     at Request._callback (/Users/jon.laing/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
28 verbose stack     at Request.self.callback (/Users/jon.laing/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/request/request.js:200:22)
28 verbose stack     at emitTwo (events.js:106:13)
28 verbose stack     at Request.emit (events.js:191:7)
28 verbose stack     at Request.<anonymous> (/Users/jon.laing/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/request/request.js:1067:10)
28 verbose stack     at emitOne (events.js:101:20)
28 verbose stack     at Request.emit (events.js:188:7)
28 verbose stack     at IncomingMessage.<anonymous> (/Users/jon.laing/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/request/request.js:988:12)
29 verbose statusCode 404
30 verbose pkgid @exponent/ex-navigation
31 verbose cwd /Users/jon.laing/projects/fakeproj
32 error Darwin 14.5.0
33 error argv "/Users/jon.laing/.nvm/versions/node/v6.5.0/bin/node" "/Users/jon.laing/.nvm/versions/node/v6.5.0/bin/npm" "install" "--save" "@exponent/ex-navigation" "--registry=https://registry.npmjs.org/"
34 error node v6.5.0
35 error npm  v2.15.6
36 error code E404
37 error 404 User not found : @exponent/ex-navigation
37 error 404
37 error 404 '@exponent/ex-navigation' is not in the npm registry.
37 error 404 You should bug the author to publish it (or use the name yourself!)
37 error 404
37 error 404 Note that you can also install from a
37 error 404 tarball, folder, http url, or git url.
38 verbose exit [ 1, true ]
```

**Comment by jonlaing** [comment]
Never mind, there must be something wrong with my .npmrc settings. I was able to get everything fine after just removing my .npmrc file. Leaving this here for posterity in case anyone else is as frustrated as me, looking in futility for solutions on Google.

**Comment by jonlaing** [comment]
Okay, for anyone who ends up landing here pissed that their npm won't install the things they need, what happened is that my job made me set some funky .npmrc settings, specifically the `always-auth` settings. It was using credentials for the custom registry, and it screwed me up when looking at the default registry. 

*To fix the issue,* I copied the .npmrc out of my home directory and put it in each project that needed it, then deleted the .npmrc from my home directory. Worked like a charm.
