### ISSUE TITLE
Tests Fail for Components that Use ex-navigation

### ISSUE THREAD

**Issue by joncursi** [exponentjs/ex-navigation#45]
When running mocha tests on components that contain `StackNavigation` components somewhere in the tree, the test will error out. Here's an example of a valid Enzyme test failing due to inability to process this package:

```
$ mocha --require imports/ui/helpers/test/setup.js --compilers js:babel-register --recursive imports/**/*.tests.js --reporter spec

/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/@exponent/ex-navigation/src/ExNavigationStyles.js:33
sceneAnimations:CardStackStyleInterpolator.forHorizontal,
                                          ^

TypeError: Cannot read property 'forHorizontal' of undefined
    at Object.<anonymous> (ExNavigationStyles.js:33:20)
    at Module._compile (module.js:541:32)
    at Module.replacementCompile (/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/append-transform/index.js:63:13)
    at loader (/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/babel-register/lib/node.js:148:5)
    at require.extensions.(anonymous function) (/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/babel-register/lib/node.js:158:7)
    at Object.<anonymous> (/Users/jcursi/Sites/joncursi/redbirdNative/node_modules/append-transform/index.js:67:4)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by joncursi** [comment]
Note that my `setup.js` file for mocha already denotes pre-compilation of this package before running the test, yet it still fails.

```
// setup.js

import fs from 'fs';
import path from 'path';
import register from 'babel-core/register';

// Ignore all node_modules except these
const modulesToCompile = [
  '@exponent/ex-navigation',
  'react-clone-referenced-element',
  'react-native',
  'react-native-material-design',
  'react-native-mock',
].map((moduleName) => new RegExp(`/node_modules/${moduleName}`));

const rcPath = path.join(__dirname, '../../../..', '.babelrc');
const source = fs.readFileSync(rcPath).toString();
const config = JSON.parse(source);

config.ignore = (filename) => {
  if ((/\/node_modules\//).test(filename)) {
    const matches = modulesToCompile.filter((regex) => regex.test(filename));
    const shouldIgnore = matches.length === 0;
    return shouldIgnore;
  }
  return false;
};

register(config);

// Setup mocks
require('react-native-mock/mock');
```

**Comment by joncursi** [comment]
Update: I've isolated the failures to components that use the `@withNavigation` decorator. There needs to be a way to mock this somehow for the tests, but I'm not sure how.

```jsx
import { withNavigation } from '@exponent/ex-navigation';

@withNavigation
export default class X extends Component {
  ...
}
```

**Comment by joncursi** [comment]
Theoretically this issue would be resolved if we could connect to ex-navigation's redux store, as that would eliminate the need for `@withNavigation` altogether.

Related:
https://github.com/exponentjs/ex-navigation/issues/44
https://github.com/exponentjs/ex-navigation/issues/39

**Comment by skevy** [comment]
@joncursi is there any way you could provide a small example repo that isolates this case? we don't use mocha @ exponent, so it's difficult for me to test this without code

**Comment by sibelius** [comment]
@joncursi did u solve ur issue?

**Comment by damusnet** [comment]
This did the trick for me to run my mocha tests again after installing `@exponent/ex-navigation`:

    mockery.registerMock('@exponent/ex-navigation', {
      createRouter: () => {},
    });

Not fully published yet, but see this [other issue](http://stackoverflow.com/questions/38292512/how-to-mock-third-party-react-native-nativemodules) for more info.

**Comment by sibelius** [comment]
I think https://github.com/lelandrichardson/react-native-mock provides a lot of mocked versions of the component

Otherwise, jest automock all the component itself, making in much easier to test

**Comment by damusnet** [comment]
Agreed, however `lelandrichardson/react-native-mock` only mocks `react-native` core native modules, not third party libraries, and yes, while Jest has become really nice to work with thanks to its handy mocking feature, you can't alway make the switch from your testing library (Mocha in this case).

**Comment by sibelius** [comment]
there are some really good codemods to help in this case

https://github.com/skovhus/jest-codemods

**Comment by Dashue** [comment]
Hitting this error.

TypeError: Cannot read property 'pushListener' of undefined
      
      at ExNavigationAndroidBackButtonBehavior.enable (node_modules\@exponent\ex-navigation\src\ExNavigationAndroidBackButtonBehavior.js:55:14)
      at ExNavigationAndroidBackButtonBehavior.componentDidMount (node_modules\@exponent\ex-navigation\src\ExNavigationAndroidBackButtonBehavior.js:29:6)
      at node_modules\react-test-renderer\lib\ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules\react-test-renderer\lib\ReactCompositeComponent.js:75:12)
      at node_modules\react-test-renderer\lib\ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules\react-test-renderer\lib\CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules\react-test-renderer\lib\ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules\react-test-renderer\lib\Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules\react-test-renderer\lib\Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules\react-test-renderer\lib\ReactTestMount.js:69:27)

So far I have this in my test

```javascript
jest.mock("bugsnag-react-native", () => 'BugSnag')
jest.mock('react-native-intercom', () => 'Intercom')
jest.genMockFromModule('@exponent/ex-navigation')

import 'react-native';
import React from 'react';
import LoginScreen from '../../app/Screens/loginScreen';

import renderer from 'react-test-renderer';

test('renders correctly', () => {
  const tree = renderer.create(
    <LoginScreen />
  ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

And this in my package.config
```
"jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|bugsnag-react-native|expo|@expo/*|exponent|@exponent/*)"
    ],
```

Thanks for any input!
